version: '3'
services:
    # First container to run the app
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3003:3000"
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true
    # Second container to run tests (no ports needed)
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
